name: ci

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        optimize: [Debug, ReleaseSafe, ReleaseFast]
    name: test ${{ matrix.optimize }}
    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v2
        with:
          version: 0.16.0
      - run: zig build test -Doptimize=${{ matrix.optimize }} --summary all

  example:
    runs-on: ubuntu-latest
    name: examples build
    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v2
        with:
          version: 0.16.0
      - run: zig build -Doptimize=ReleaseFast
